name: 'Mark and maybe close stale issues and PRs'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 90  # 3 months
          days-before-close: 180  # 6 months
          operations-per-run: 60
          debug-only: true
