name: 'Mark and maybe close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'
    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 180  # 6 months
          days-before-close: 270  # 9 months
          debug-only: true
